### ISSUE TITLE
ReactNative 0.63的Dialog Exception

### ISSUE THREAD

**Issue by MrLaibin** [Meituan-Dianping/beeshell#109]
![image](https://user-images.githubusercontent.com/13825960/87617570-56716200-c74a-11ea-914f-1920eae74354.png)

怎么才能自己构建项目。
npm install 无法找到mrn相关的包

**Comment by MrLaibin** [comment]
FadeAnimated.tsx 63行的getPropertyValue有时候会返回null，只需要判断一下，null时返回0就好了。

**Comment by Damoness** [comment]
+1

**Comment by HeyShinner** [comment]
我打算从项目中移除 beeshell 了，因为已经很久没更新代码了，是不是凉了？

**Comment by Damoness** [comment]
> 不是凉了？



> 我打算从项目中移除 beeshell 了，因为已经很久没更新代码了，是不是凉了？

又是一个KPI项目，😔

**Comment by MrLaibin** [comment]
@xy371661665 已弃坑😄，拥抱flutter
