### ISSUE TITLE
@mrn 部分开源 !

### ISSUE THREAD

**Issue by iShawnWang** [Meituan-Dianping/beeshell#110]
这... 算是开源项目吗... 感觉是为了 kpi 开源一波... 
本地无法构建调试和二次开发... `@mrn` 不开源可以发不压缩的版本到 npm 吗 ?

**Comment by MrLaibin** [comment]
兄弟，可以把mrn相关的全部删除，替换为react-native。beeshell是JS层的，没有mrn估计就是少一些性能加成。mrn感觉开源的可能性会很小。
我发现美团也还没做dark mode。

**Comment by iShawnWang** [comment]
@MrLaibin 感谢 ~ 

emmm, beeshell 更新不积极有点可惜...
