### ISSUE TITLE
Modal无法显示

### ISSUE THREAD

**Issue by Keizai** [Meituan-Dianping/beeshell#18]
### 
跳转到另一个界面后再返回有modal的界面，modal.open()无法显示
modal
### 环境
- 手机: iPhone 6 simulator
- 系统：iOS 10.2
- beeshell版本：1.0.1
- 其他版本信息
"react-native-navigation": "^2.0.2634"

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

使用的导航：react-native-navigation

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Topview
    in RCTView (at View.js:44)
    in Unknown (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

**Comment by wxlworkhard** [comment]
是不是因为 Modal 组件还没有 mounted 完成？
