### ISSUE TITLE
禁止Longlist onEndReached方法

### ISSUE THREAD

**Issue by huangxiaohao** [Meituan-Dianping/beeshell#21]
### 问题是什么
问题的具体描述，尽量详细
您好，在使用Longlist时，进入页面后会请求一次数据接口，但是onEndReached也会请求一次，导致进入页面后会有两次数据接口请求，请问如何禁止onEndReached方法
### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段
```
<Longlist
    data={list}
      renderItem={this.handleRenderItem.bind(this)}
      hasRefreshControl={true}
      onEndReached={this.refreshState}
      onRefresh={this.refreshState}           
/>
```
### 其他
其他信息

**Comment by huangxiaohao** [comment]
我现在如果直接不调用onEndReached方法，会报错

![simulator screen shot - iphone 6 - 2018-11-15 at 11 11 24](https://user-images.githubusercontent.com/13390763/48527828-77274b80-e8c7-11e8-875a-cdd8ae2215ef.png)

**Comment by wxlworkhard** [comment]
第一屏的数据超出屏幕，就不会触发 onEndReached 方法了
