### ISSUE TITLE
Radio设置的Laber不显示，只显示前面的勾勾

### ISSUE THREAD

**Issue by ShuChangSC** [Meituan-Dianping/beeshell#26]
### 问题是什么
Radio设置的Laber不显示，只显示前面的勾勾

### 环境
- 手机: Android
- 系统：7.1.1
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by wxlworkhard** [comment]
属性名是 label
