### ISSUE TITLE
slideModal不能适配全面屏

### ISSUE THREAD

**Issue by ShuChangSC** [Meituan-Dianping/beeshell#28]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: RedMi 6A
- 系统：android  8.1.0
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
slideModal从底部弹出，在不开启全面屏的情况下正常，开启全面屏之后，距离底部会出现一定距离，距离应该等于底部虚拟按键高度

### 其他
其他信息

**Comment by wxlworkhard** [comment]
因为 RN 给出的屏幕高度 Dimensions.get('window').height 在某些 Android 机器上并不是真正的可视区域，所以 SlideModal 不能覆盖全屏。
5 月 3 日发布 2.0，将 screenHeight 属性暴露给用户，用户自定义可视区（屏幕）高度

**Comment by liuyunzyj** [comment]
@wxlworkhard 如何使用screenHeight适配全面屏？

**Comment by liuyunzyj** [comment]
@wxlworkhard 因为我这个是需要满屏显示的

**Comment by liuyunzyj** [comment]
问题：我楼上哥们一样slideModal从底部弹出，在不开启全面屏的情况下正常，开启全面屏之后，距离底部会出现一定距离，距离应该等于底部虚拟按键高度

**Comment by Damoness** [comment]
> 问题：我楼上哥们一样slideModal从底部弹出，在不开启全面屏的情况下正常，开启全面屏之后，距离底部会出现一定距离，距离应该等于底部虚拟按键高度

设置 screenHeight= {Dimensions.get( 'screen').height}

**Comment by liuyunzyj** [comment]
设置 screenHeight= {Dimensions.get( 'screen').height}试过了，全面屏和不全面屏弄出来的效果有差距

**Comment by Damoness** [comment]
> 设置 screenHeight= {Dimensions.get( 'screen').height}试过了，全面屏和不全面屏弄出来的效果有差距

是获取screen的高度,不是window

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/61033466-246e4700-a3f6-11e9-94b1-36929d778536.png)
一样的，全面屏还是一样

**Comment by liuyunzyj** [comment]
不是全面的话里面的容器可以覆盖整个屏幕，如果是全面屏的话底部的tab栏覆盖不了
