### ISSUE TITLE
这个库还维护吗，半年未更新了

### ISSUE THREAD

**Issue by ch957869975** [Meituan-Dianping/beeshell#29]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by nongh90** [comment]
本来还想用一下，发现半年没更新了

**Comment by wxlworkhard** [comment]
5月3号有新的版本发布

**Comment by ch957869975** [comment]
@wxlworkhard 期待

**Comment by misty-rain** [comment]
> 5月3号有新的版本发布
说好的5月3号发布新版本呢

**Comment by wxlworkhard** [comment]
5月6日正式发布
