### ISSUE TITLE
为什么react native 的npm库里面的版本的组件比 你们这边github里面的组件少那么多。发布版和开源没有同步吗?

### ISSUE THREAD

**Issue by jolly-wu** [Meituan-Dianping/beeshell#30]

**Comment by wxlworkhard** [comment]
是最新 2.0 版本吗？1.0 版本组件少很多

**Comment by jolly-wu** [comment]
npm 上面应该是1.0的。2.0版本要怎么用上呢？我的rn是0.59版本


 
---原始邮件---
发件人: "wxlworkhard"<notifications@github.com>
发送时间: 2019年5月11日(星期六) 晚上11:14
收件人: "Meituan-Dianping/beeshell"<beeshell@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"jolly-wu"<324152492@qq.com>;
主题: Re: [Meituan-Dianping/beeshell] 为什么react native 的npm库里面的版本的组件比 你们这边github里面的组件少那么多。发布版和开源没有同步吗? (#30)



是最新 2.0 版本吗？1.0 版本组件少很多

**Comment by wxlworkhard** [comment]
npm install beeshell@latest -S
