### ISSUE TITLE
Scrollpicker 卡顿3秒，动画不流畅

### ISSUE THREAD

**Issue by jolly-wu** [Meituan-Dianping/beeshell#31]
使用基于BottomModel和Scrollpicker的弹出效果太卡了。有3秒左右的卡顿，RN的版本是0.59，有优化的空间吗?

**Comment by wxlworkhard** [comment]
在真机还是模拟器？iOS 还是 Android？

**Comment by jolly-wu** [comment]
android真机。picker底层有做view的复用吗

**Comment by wxlworkhard** [comment]
Android 机型说下啊，我们测试下，我们业务倒是没出现过这么严重的卡顿

**Comment by jolly-wu** [comment]
我的机器是红米note7，是debug模式下面，非常卡。release打包的app模式下，比较流畅了，不过动画上面有点飘，不太连贯。

**Comment by wxlworkhard** [comment]
iOS 真机、模拟器都正常吗？

**Comment by wxlworkhard** [comment]
iOS 平台卡顿严重吗？其他 Android 机器卡顿严重吗？

**Comment by jolly-wu** [comment]
都还好。release模式比较流畅。


 
---原始邮件---
发件人: "wxlworkhard"<notifications@github.com>
发送时间: 2019年5月29日(星期三) 中午1:17
收件人: "Meituan-Dianping/beeshell"<beeshell@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"jolly-wu"<324152492@qq.com>;
主题: Re: [Meituan-Dianping/beeshell] Scrollpicker 卡顿3秒，动画不流畅 (#31)



iOS 平台卡顿严重吗？其他 Android 机器卡顿严重吗？

**Comment by wxlworkhard** [comment]
可能因为业务逻辑太重，加上 debug 模式下性能本来就差
