### ISSUE TITLE
使用官方组件import { Rate } from 'beeshell';报错，使用react-native工程版本是0.59.8

### ISSUE THREAD

**Issue by liuyunzyj** [Meituan-Dianping/beeshell#34]
![image](https://user-images.githubusercontent.com/40293335/58677641-5e781200-838f-11e9-97ab-d6b72b9f5bfb.png)

**Comment by liuyunzyj** [comment]
使用的组件库有 "dependencies": {
    "@ant-design/react-native": "^3.1.8",
    "beeshell": "^2.0.4",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-image-crop-picker": "^0.24.0",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-simple-store": "^1.3.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "redux-persist": "4.8.2",
    "redux-promise-middleware": "^4.4.1",
    "redux-thunk": "^2.3.0",
    "teaset": "^0.6.3"
  },

**Comment by wxlworkhard** [comment]
看下 node_modules/beeshell/package.json 的版本号呢，其他组件能正常 import 吗？

**Comment by liuyunzyj** [comment]
不能
![image](https://user-images.githubusercontent.com/40293335/58693103-9e0c2180-83c2-11e9-81f0-ecfedd435da0.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/58693189-c85ddf00-83c2-11e9-8dd0-c2a226f201d3.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/58693216-dd3a7280-83c2-11e9-9eda-dae52b3cc874.png)
![image](https://user-images.githubusercontent.com/40293335/58693222-e1ff2680-83c2-11e9-8a7f-3e1864c4778a.png)
![image](https://user-images.githubusercontent.com/40293335/58693231-e62b4400-83c2-11e9-9620-7b70d9fb6b2a.png)

**Comment by liuyunzyj** [comment]
@wxlworkhard

**Comment by liuyunzyj** [comment]
@wxlworkhard 你这边是不是和我这边用的组件包冲突了，因为我尝试重新构建react native项目直接引入是可以的，

**Comment by liuyunzyj** [comment]
"dependencies": {
    "@ant-design/react-native": "^3.1.8",
    "beeshell": "^2.0.4",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-image-crop-picker": "^0.24.0",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-simple-store": "^1.3.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "redux-persist": "4.8.2",
    "redux-promise-middleware": "^4.4.1",
    "redux-thunk": "^2.3.0",
    "teaset": "^0.6.3"
  },

**Comment by wxlworkhard** [comment]
beeshell 只依赖 moment 应该不会有什么冲突。
按需引入的方式可以吗？
把 node_modules、package-lock.json 删了重装下呢？

**Comment by liuyunzyj** [comment]
尝试过删除了，没有用，



------------------ 原始邮件 ------------------
发件人: "wxlworkhard"<notifications@github.com>; 
发送时间: 2019年6月2日(星期天) 下午4:57
收件人: "Meituan-Dianping/beeshell"<beeshell@noreply.github.com>; 
抄送: "蒗，，得妮&#x2661;"<1694382922@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Meituan-Dianping/beeshell] 使用官方组件import { Rate } from 'beeshell';报错，使用react-native工程版本是0.59.8 (#34)




beeshell 只依赖 moment 应该不会有什么冲突。
 按需引入的方式可以吗？
 把 node_modules、package-lock.json 删了重装下呢？

**Comment by liuyunzyj** [comment]
@wxlworkhard 可以出一个索引列表组件吗？

**Comment by wxlworkhard** [comment]
新开个 issue 吧，把具体的功能描述下，最好有 UI 或者参考🙃
