### ISSUE TITLE
NavigationBar 组件 不能设置文字大小 颜色 返回图标也设置不了颜色。

### ISSUE THREAD

**Issue by yrjwcharm** [Meituan-Dianping/beeshell#36]
<NavigationBar
                title={props.name ? props.name : '没写标题'}
                backLabel={props.back?'返回':''}
                forwardLabel={props.rightText?props.rightText:''}
                onPressBack={() => {
                    Actions.pop()
                }}
                onPressForward={props.onPress}
                style={{height: isIphoneX ? px2dp(176) : px2dp(130),backgroundColor:'transparent'}}
            />

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/59182366-25fce300-8b9c-11e9-91ba-c17396357852.png)

**Comment by yrjwcharm** [comment]
设置不了字体大小 颜色  返回图标颜色

**Comment by yrjwcharm** [comment]
这个问题有点致命啊

**Comment by yrjwcharm** [comment]
大神 大佬 赶快解决 啊

**Comment by yrjwcharm** [comment]
坐等 更新

**Comment by wxlworkhard** [comment]
0612 晚上更新

**Comment by wxlworkhard** [comment]
以支持相关功能的定制化 beeshell@2.0.5

**Comment by yrjwcharm** [comment]
You are the best!!!

**Comment by wxlworkhard** [comment]
哈哈
