### ISSUE TITLE
Dropdown 组件设置 cancelable={false}点击蒙层依然消失

### ISSUE THREAD

**Issue by liuyunzyj** [Meituan-Dianping/beeshell#37]
<Dropdown
                ref={c => {
                  this.slideModal2 = c;
                }}
                offsetX={0}
                style={{ width: screenW, height: setSpText(150) }}
                offsetY={this.state.offsetY2}
                cancelable={false}
                value={this.state.value}
                data={this.state.data}
                onChange={this.onChange}
              />

**Comment by liuyunzyj** [comment]
@wxlworkhard 望快点修复这个bug

**Comment by wxlworkhard** [comment]
beeshell@2.0.6
