### ISSUE TITLE
android下，通过美团APP扫码无法查看

### ISSUE THREAD

**Issue by soulmatecm** [Meituan-Dianping/beeshell#38]
android下，通过美团APP扫码无法查看，ios下面可以，android我拿了华为的几个型号的手机试了都不行。

**Comment by soulmatecm** [comment]
而且我试了一下actionsheet，dialog组件，点击打开时，为何如此之卡（在android模拟器上），基础dialog要1秒才显示出来？请问是什么原因呢？

**Comment by julytian** [comment]
ios扫码也是

**Comment by radish-angel** [comment]
ios，华为扫码不能看

**Comment by 2788** [comment]
我刚才试了  苹果 android 都不行

**Comment by soulmatecm** [comment]
> 我刚才试了 苹果 android 都不行

ios的话，你们看下是不是美团版本是否是最新版本，我这边是可以的。但是android我拿了几个不同型号手机，升级了最新版，也都扫不出来。

**Comment by 2788** [comment]
> > 我刚才试了 苹果 android 都不行
> 
> ios的话，你们看下是不是美团版本是否是最新版本，我这边是可以的。但是android我拿了几个不同型号手机，升级了最新版，也都扫不出来。

我刚才去下载了最新版本的美团  ios 还是看不了  我服了

**Comment by minicase** [comment]
ios 和 安卓都不行的

**Comment by wxlworkhard** [comment]
是手机的问题吗？我们的测试机 iOS、Android 都可以啊

**Comment by wxlworkhard** [comment]
美团 APP 版本要求：Android（v9.13.202）iOS（v10.0.200）
试一下行不行

**Comment by imlida** [comment]
确实无法打开

**Comment by frontendWangqun** [comment]
> 美团 APP 版本要求：Android（v9.13.202）iOS（v10.0.200）
> 试一下行不行

现在ios扫描打不开，页面出错啊，这个项目还有人维护吗？

**Comment by wxlworkhard** [comment]
@frontendWangqun 截图看下美团 APP 版本
