### ISSUE TITLE
安卓苹果最新app都看不了演示

### ISSUE THREAD

**Issue by leoxiaoping** [Meituan-Dianping/beeshell#40]
安卓苹果最新app都看不了演示
还有怎么在本地运行 example

**Comment by wxlworkhard** [comment]
在本地是无法运行示例的，因为有内部依赖。
扫描二维码后是什么样子，给个截图看下吧

**Comment by wxlworkhard** [comment]
美团 APP 版本要求：Android（v9.13.202）iOS（v10.0.200）
试一下行不行

**Comment by minicase** [comment]
![f8038e0bf7a14b95fc89c827d34c618](https://user-images.githubusercontent.com/9739133/59846910-a937e900-9393-11e9-9588-c6198b04c09a.png)
![0647ef40dfad77f9e6f30e3a9e58892](https://user-images.githubusercontent.com/9739133/59846913-aa691600-9393-11e9-8ce0-563fae0a2da0.jpg)

**Comment by wxlworkhard** [comment]
@minicase 版本不对，Android 用 v9.13.202 这个版本

**Comment by leoxiaoping** [comment]
@wxlworkhard  谢谢啦，还是支持国产UI组件库啊，看着顺眼

**Comment by wxlworkhard** [comment]
@leoxiaoping 感谢反馈，合作愉快

**Comment by Oshima-Ryu** [comment]
美团App 10.0.801 （小米9），无法访问
