### ISSUE TITLE
组件的演示用最新的app真的不能查看

### ISSUE THREAD

**Issue by leoxiaoping** [Meituan-Dianping/beeshell#41]
组件的演示用最新的app真的不能查看

![f8038e0bf7a14b95fc89c827d34c618](https://user-images.githubusercontent.com/9739133/59842681-99b3a280-9389-11e9-939d-336cbfa0cfdf.png)

**Comment by wxlworkhard** [comment]
美团 APP 版本要求：Android（v9.13.202）iOS（v10.0.200）

**Comment by wxlworkhard** [comment]
https://github.com/Meituan-Dianping/beeshell/issues/40
