### ISSUE TITLE
import Longlist from 'beeshell/dist/components/Longlist';这个组件当下拉加载的时候无数据了，官方默认的是 --无更多数据，那我如何自定义修改这部分的内容呢

### ISSUE THREAD

**Issue by liuyunzyj** [Meituan-Dianping/beeshell#43]

**Comment by wxlworkhard** [comment]
升级 beeshell@2.0.7
使用 renderFooter 属性，自定义页脚渲染区域

代码如下：
```
renderFooter={(loading, data, total) => {
    if (data.length && data.length >= total) {
        // 无更多数据的情况
        return <Text style={{ color: 'red' }}>hello world !</Text>
    }
}}
```

**Comment by liuyunzyj** [comment]
@wxlworkhard 望官方快点解决这个问题

**Comment by liuyunzyj** [comment]
@wxlworkhard 官方上拉加载的动画如何自定义呢

**Comment by wxlworkhard** [comment]
@liuyunzyj 也是 renderFooter 这个属性
这个方法的第一个参数 loading 表示是否正在加载，在 loading = true 时，可以自定义加载动画

**Comment by liuyunzyj** [comment]
@wxlworkhard  也是 renderFooter 这个属性
这个方法的第一个参数 loading 表示是否正在加载，在 loading = true 时，可以自定义加载动画这个无效啊

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/60075903-dbad6180-9758-11e9-9776-11b3d0c71557.png)
这个loading一直都是false

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/60075944-f5e73f80-9758-11e9-9b9a-b82119ccd5e5.png)

**Comment by wxlworkhard** [comment]
有没有触发，加载数据方法的执行呢

**Comment by liuyunzyj** [comment]
@wxlworkhard 有的，我想到其他办法解决了，

**Comment by wxlworkhard** [comment]
ok

**Comment by liuyunzyj** [comment]
@wxlworkhard 我用的SlideModal这个组件在ios上点击蒙层无法消失
