### ISSUE TITLE
Slider   没有 这个属性 thumbImage

### ISSUE THREAD

**Issue by yrjwcharm** [Meituan-Dianping/beeshell#47]

**Comment by yrjwcharm** [comment]
不能自定义滑块样式啊 比如我想让滑块以图片的方式显示。

**Comment by wxlworkhard** [comment]
使用 renderThumb 属性，自定义滑块，返回一个 ReactElement

```
        <Slider
            max={1500}
            value={500}
            thumbSize={50}
            renderThumb={() => {
              return (
                <View
                  style={{
                    width: 50,
                    height: 50,
                    borderRadius: 50,
                    backgroundColor: variables.mtdBrandDanger,
                    opacity: 0.7
                  }}>
                </View>
              )
            }}
          />
```
注意返回的 ReactElement 的宽高要相等，并且等于 thumbSize 属性的值

**Comment by yrjwcharm** [comment]
@wxlworkhard  I admire you very much.

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/60146572-ac503080-97fc-11e9-879f-4ac7803d9e97.png)

**Comment by yrjwcharm** [comment]
报了这个错  最大值 和 最小值 是不是不能相等？

**Comment by yrjwcharm** [comment]
这个 min值 必须要小于 value 值呢 不能相等吗？

**Comment by yrjwcharm** [comment]
这个最大值 是不是必须大于0呢？

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/60147283-6a74b980-97ff-11e9-98d9-99446d2b7fb9.png)

**Comment by yrjwcharm** [comment]
我把这四个值同时设置 为0  就报上面的错误。 因为 第一次 走渲染 render() 方法的时候 初始化 都为0

**Comment by yrjwcharm** [comment]
最小值 min 是不是不能和 最大值max 相同

**Comment by yrjwcharm** [comment]
这个最大值 应该和 最小值也应该有相同的时候吧。 希望尽快 解决下吧。

**Comment by yrjwcharm** [comment]
@wxlworkhard  大佬今天可以解决吗
![image](https://user-images.githubusercontent.com/34397383/60148324-2b486780-9803-11e9-8cd7-38f641fc654e.png)

**Comment by yrjwcharm** [comment]
官方组件Slider 各种Bug  靠你了。@wxlworkhard

**Comment by wxlworkhard** [comment]
升级版本 beeshell@2.0.9
问题修复 https://github.com/Meituan-Dianping/beeshell/commit/a9b4524907d2cc8bf6d2b41ae0183fe7553732b4

**Comment by yrjwcharm** [comment]
@wxlworkhard   Thank you very much.
