### ISSUE TITLE
Modal里面无法使用TextInput输入中文

### ISSUE THREAD

**Issue by Wuge11** [Meituan-Dianping/beeshell#48]
在使用TextInput的时候不能输入中文

**Comment by wxlworkhard** [comment]
能输入英文、数字，不能输入中文？

**Comment by Wuge11** [comment]
是的，像是自动按了回车一样

**Comment by weirDozzz** [comment]
这是TextInput组件本身的缺陷，参考https://reactnative.cn/docs/textinput/#value

**Comment by Wuge11** [comment]
> 这是TextInput组件本身的缺陷，参考https://reactnative.cn/docs/textinput/#value

好像不是这个问题，我换成自带 RN 的 Modal 就不会，可能是 Modal 的 cancelable，然后输入的时候每打一个字就触发一次导致回车了

**Comment by wxlworkhard** [comment]
Modal 的底层依赖 Topview 组件的问题，已经修复，请升级 beeshell@2.0.11

**Comment by Wuge11** [comment]
> Modal 的底层依赖 Topview 组件的问题，已经修复，请升级 beeshell@2.0.11

好的谢谢！
