### ISSUE TITLE
BottomModal组件请优化一下，问题是：弹出来的时候的动画有点卡顿，体验不是很友好，ios和安卓都有此问题

### ISSUE THREAD

**Issue by frontendWangqun** [Meituan-Dianping/beeshell#49]
BottomModal组件请优化一下，问题是：弹出来的时候的动画有点卡顿，体验不是很友好，ios和安卓都有此问题

**Comment by wxlworkhard** [comment]
用美团 APP 扫码体验的吗？

**Comment by frontendWangqun** [comment]
> 用美团 APP 扫码体验的吗？

美团现在扫码ios和Android都是页面出错，在ios模拟器上会有卡卡的效果

**Comment by wxlworkhard** [comment]
美团 APP 版本要求：Android（v9.13.202）iOS（v10.0.200）
能下载指定的版本试试吗？
