### ISSUE TITLE
Slider 滑动时 value 很随意的去增长 。没有按照 step 的值进行迭代

### ISSUE THREAD

**Issue by yrjwcharm** [Meituan-Dianping/beeshell#52]

**Comment by yrjwcharm** [comment]
这个很着急 因为项目中用到了你的组件了。麻烦你了

**Comment by weirDozzz** [comment]
麻烦提供下完整的复现实例方便我们排查问题

**Comment by yrjwcharm** [comment]
@weirDozzz    <Slider renderThumb={()=>{
                        return  <Image source={Images.thumbImage} style={{width:px2dp(96),height:px2dp(96)}} resizeMode={'contain'}/>
                    }}  thumbSize={px2dp(96)} minTrackColor={"#ffc873"} maxTrackColor={"#f3f4f6"} onChange={(value)=>this._onValueChanged(value)}
                               step={rise} value={loanAmount1} max={loanmoneyend1}
                              min={loanmoneystart1} />

**Comment by yrjwcharm** [comment]
![Uploading image.png…]()

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/60408116-2531fc80-9bf0-11e9-8d42-61b82abe33e3.png)

**Comment by yrjwcharm** [comment]
@weirDozzz   就是 随便 写个例子  。比如 我上便最小值 是 100 最大值 是1000  step 值 为 50 每次增加不统一。按道理来说 应该 是  300  350 400 450 500 .... 这种形式 递增啊。

**Comment by wxlworkhard** [comment]
升级 2.0.10
