### ISSUE TITLE
Android 的 BottomModal 会被虚拟按键挡住

### ISSUE THREAD

**Issue by Wuge11** [Meituan-Dianping/beeshell#54]
![image](https://user-images.githubusercontent.com/46960533/60329225-87a5b580-99c2-11e9-9779-54e11bad7a67.png)
![image](https://user-images.githubusercontent.com/46960533/60329269-9db37600-99c2-11e9-9481-5f11f2c7b4f9.png)

**Comment by wxlworkhard** [comment]
通过 styles 属性解决遮挡问题，解决方式如下：
```
<BottomModal
          styles={{
            root: {
              bottom: 0,
              height: null
            }
          }}>
</BottomModal>
```

**Comment by Wuge11** [comment]
> 通过 styles 属性解决遮挡问题，解决方式如下：
> 
> ```
> <BottomModal
>           styles={{
>             root: {
>               bottom: 0,
>               height: null
>             }
>           }}>
> </BottomModal>
> ```

好的谢谢！
