### ISSUE TITLE
为什么你demo里面这个Longlist第一次进入页面就会触发onendreached，而且这个行为好像也不是固定的，有时候可以有时候就不行？

### ISSUE THREAD

**Issue by soulmatecm** [Meituan-Dianping/beeshell#59]

**Comment by soulmatecm** [comment]
就是你们提供的demo好像确实是每次进入页面都触发onendreached，但是我自己使用这个Longlist并不会触发。

**Comment by wxlworkhard** [comment]
onEndReached 触发时机，跟页面数据以及滑动位置有关系，demo 进入页面时，第一屏数据很少，触发了 onEndReached 的执行
