### ISSUE TITLE
TreeView组件 按照官方demo 显示异常

### ISSUE THREAD

**Issue by mrossZ** [Meituan-Dianping/beeshell#65]
首次渲染页面没问题，点击根目录后就会报错。就是说 不显示子节点。

`Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at TouchableOpacity.js:308)
    in TouchableOpacity (created by TreeView)
    in RCTView (at View.js:35)
    in View (created by TreeView)
    in RCTView (at View.js:35)
    in View (created by TreeView)
    in RCTView (at View.js:35)
    in View (created by TreeView)
    in RCTView (at View.js:35)
    in View (created by TreeView)
    in RCTView (at View.js:35)
    in View (created by TreeView)
    in TreeView (at treeView.js:42)
    in TreeViewScreen
    in RCTView (at View.js:35)
    in View
    in Unknown (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)`

**Comment by wxlworkhard** [comment]
Text strings must be rendered within a component.
把文案用 <Text> 标签包裹一下

**Comment by mrossZ** [comment]
> Text strings must be rendered within a component.
> 把文案用 `<Text>` 标签包裹一下

无效
